### ISSUE TITLE
No Output is given on Output 2

### ISSUE THREAD

**Issue by captaingoujon** [fellinga/node-red-contrib-ui-time-scheduler#1]
When using the scheduler only output 1, "Outputs new schedule", seems to do anything
Output 2 never gives any output
Really liking the dashboard system, will be great for my project

The flow I'm using is below

`[{"id":"92432b2a.a282a8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"68a5924d.c5851c","type":"comment","z":"92432b2a.a282a8","name":"### This scenario is permanent and requires a file to read an write to ###","info":"","x":360,"y":440,"wires":[]},{"id":"8b78b561.41dae8","type":"inject","z":"92432b2a.a282a8","name":"FireAfterReboot","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":200,"y":500,"wires":[["301cea20.0ae426"]]},{"id":"988a4680.f98f38","type":"ui_time_scheduler","z":"92432b2a.a282a8","group":"c66eb395.fc787","name":"Pump","order":2,"width":"3","height":"6","x":710,"y":500,"wires":[["c8fdc395.71a1b","57bf3c62.a67a64"],["3fbdc154.4e6bde","f428d818.6068a8"]]},{"id":"3fbdc154.4e6bde","type":"ui_switch","z":"92432b2a.a282a8","name":"","label":"Pump","tooltip":"","group":"c66eb395.fc787","order":1,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":1030,"y":520,"wires":[[]]},{"id":"301cea20.0ae426","type":"function","z":"92432b2a.a282a8","name":"Get Schedule","func":"msg.payload = global.get(\"schedule\");\nreturn msg;","outputs":1,"noerr":0,"x":440,"y":500,"wires":[["988a4680.f98f38"]]},{"id":"c8fdc395.71a1b","type":"function","z":"92432b2a.a282a8","name":"Set onOff","func":"global.set(\"schedule\",msg.payload);\nreturn msg;","outputs":1,"noerr":0,"x":1040,"y":480,"wires":[[]]},{"id":"57bf3c62.a67a64","type":"debug","z":"92432b2a.a282a8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":1050,"y":440,"wires":[]},{"id":"f428d818.6068a8","type":"debug","z":"92432b2a.a282a8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":1050,"y":580,"wires":[]},{"id":"c66eb395.fc787","type":"ui_group","z":"","name":"PermDemo","tab":"885c13b9.5ae63","order":5,"disp":true,"width":"6","collapse":false},{"id":"885c13b9.5ae63","type":"ui_tab","z":"","name":"Scheduler Demo","icon":"dashboard","order":1,"disabled":false,"hidden":false}]`

**Comment by fellinga** [comment]
Okay so the debug node at output 1, shows the following payload after I added one timer (default settings) via the dashboard (with your flow):

`"{"timers":[{"starttime":42720000,"endtime":43020000,"days":[0,0,0,0,0,1,0],"sendContinuous":true,"onlySendStart":{"isActivated":false,"valueToRun":true}}]}"`

and output 2 sends

`true`

at the defined start time which is correct.


![Demo](https://user-images.githubusercontent.com/26927863/94261765-ad599b80-ff32-11ea-866e-55ee685ea867.png)

**Comment by captaingoujon** [comment]
This is the same methodology as I used to test but I do not receive anything on the second debug node
`"{"timers":[{"starttime":49140000,"endtime":49440000,"days":[0,0,0,0,0,1,0],"sendContinuous":true,"onlySendStart":{"isActivated":false,"valueToRun":true}}]}"`
![image](https://user-images.githubusercontent.com/10260925/94273924-f6165200-ff3c-11ea-9b86-69fe7c2c9f77.png)
![image](https://user-images.githubusercontent.com/10260925/94273956-ff072380-ff3c-11ea-97f4-0b802b834bd7.png)

**Comment by fellinga** [comment]
Definitely strange, since I have tested this on multiple devices and virtual machines.
Could you try to create a timer that has all days selected, and see if it works then?

What operating system/device are you using?

**Comment by captaingoujon** [comment]
Timer using all days gives same result as does setting every day 00:00 to 23:59
I'm using NodeRED docker hosted on Unraid OS

**Comment by fellinga** [comment]
So I installed an unraid trial via virtualbox and installed the node-red docker container. 
The timer didn't work as expected, but like I suspected it seemed to be a date/time problem.

Can you add this to your flow and tell me if it outputs the correct local time?
`[{"id":"19db767e.566f9a","type":"ui_text","z":"a9305d8b.a333a","group":"50aa414d.fc336","order":2,"width":0,"height":0,"name":"","label":"TimeNow","format":"{{msg.payload}}","layout":"row-spread","x":680,"y":260,"wires":[]},{"id":"e6f5f011.5054a","type":"inject","z":"a9305d8b.a333a","name":"FireAfterReboot","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"1","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":170,"y":260,"wires":[["73735a40.187cf4"]]},{"id":"73735a40.187cf4","type":"function","z":"a9305d8b.a333a","name":"GetTime","func":"const days = ['SU','MO','TU','WE','TH','FR','SA'];\n\nconst date = new Date();\nconst today = date.getDay();\nconst currentHour = padZero(date.getHours());\nconst currentMinute = padZero(date.getMinutes());\n\nmsg.payload = days[today] + \" - \" + currentHour + \":\" + currentMinute;\nreturn msg;\n\nfunction padZero(i) {\n    return i < 10 ? \"0\"+i : i;\n}","outputs":1,"noerr":0,"initialize":"","finalize":"","x":380,"y":260,"wires":[["19db767e.566f9a"]]},{"id":"50aa414d.fc336","type":"ui_group","z":"","name":"PermDemo","tab":"681cf323.a5097c","order":5,"disp":true,"width":"6","collapse":false},{"id":"681cf323.a5097c","type":"ui_tab","z":"","name":"Scheduler Demo","icon":"dashboard","order":1,"disabled":false,"hidden":false}]`

In order to get in run, I had to change the timezone in the unraid dashboard (settings-date and time) and then !reinstall the node-red docker container. A restart had no effect. Please let me know if this helps.

**Comment by captaingoujon** [comment]
Reinstalling NodeRed docker did fix the issue
The Flow above always displayed correct local time so I'm unsure why the main flow wasn't working before
