### ISSUE TITLE
[Enhancement] Refresh = 0  ==> Send Msg update only on event TRUE/FALSE

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [fellinga/node-red-contrib-ui-time-scheduler#23]
Hi,

I do like your node and just updating my flows accordingly.  At moment you are updating every 60sec (or as specified  by REFRESH) with a MSG payload of TRUE/FALSE.

Is it possible to have the state update only when the event occurs (not every 60 secs)?  

Why do I need this (use case):
1) I have a Poolpump scheduled for 7am-8am and 7pm to 8pm
2) I can activate the Pool Pump by Alexa, however it get switched-off after max 60sec when your node is sending an update

Thanks for considering

**Comment by fellinga** [comment]
Hi,

yes there a two common possibilities:

1. Simply add an RBE node (with default, block unless value changes, setting) to the output. 
![rbe](https://user-images.githubusercontent.com/26927863/105627359-d897bd00-5e36-11eb-9014-4928f4e5d959.jpg)

2. Switch to the EVENT mode and schedule single events instead of a time frame, they will only fire at the specified time.
![event](https://user-images.githubusercontent.com/26927863/105627364-ddf50780-5e36-11eb-859b-71ff264d9722.png)

Please let me know if this helps!

**Comment by xX-Nexus-Xx** [comment]
yes, I have used the RBE node already in my flow but for some reason I get the occasional update a few ms after the initial event. Therefore I'm suppressing any update for 10sec after each new event

![image](https://user-images.githubusercontent.com/2195190/105807725-a59e2680-5ffa-11eb-92d2-514bd9e11359.png)

==> These are 2 workarounds for this refresh=0  ;-) ... but I will survive 

I tried your Option 2 as well but i have too many On/Off scenarios ;-) to use this option

great node ... keep up the good work

**Comment by fellinga** [comment]
1. is a workaround that is correct... I haven't implemented that into the node because it is just so easy to add the RBE node.
2. is perfekt solution to this problem and one of the reasons why the event mode even exists. There is no limit for On/Off scenarios, you can add as many as you want.

I did some testing today and I am not sure anymore if the RBE might actually behaves weird if no topic is set - would be nice if we could figure that out together. Can you enable the topic output within the **ui schedulers** setting and see if this changes anything to the better?

**Comment by xX-Nexus-Xx** [comment]
Yes, will do... never experienced anything wrong with RBE so far and I'm using it a lot

**Comment by fellinga** [comment]
1.9.0 now has the ability to block output unless a value changes! I'd appreciate your feedback!

**Comment by xX-Nexus-Xx** [comment]
works great !!
