### ISSUE TITLE
Ask about new Feature#2

### ISSUE THREAD

**Issue by bgaebel** [fellinga/node-red-contrib-ui-time-scheduler#25]
First: you did a great job with this package!

I want to change the name of each device from a file. I couldn't find any way to do this in the current version.
Maybe I missed this NodeRed feature.

Best regards from Germany ;)

**Comment by fellinga** [comment]
Hi bgaebel,

I am glad you like it. Thanks for your feedback.

The node red API does not allow to alter a nodes property from the UI or incoming messages (at least not in a very good way) - because you would have to hit the deploy button from the flow editor after (see [here](https://discourse.nodered.org/t/edit-node-config-from-dashboard/20495), especially knolleary's comment).

Because of that limitation I can not implement that into the node..

**Comment by fellinga** [comment]
After taking a closer look, I also noticed that any change to the device name during runtime would cause an inconsistency between the actual device name that is stored at the flow editor and the frontend. 

To answer your initial question: It is not possible to change the device name from a file and can't be added in a satisfactory way.
