### ISSUE TITLE
Enhancement request: independet starttype / endtype

### ISSUE THREAD

**Issue by PeterAustria** [fellinga/node-red-contrib-ui-time-scheduler#33]
Thanks a lot for this great node.

It would be great for my application if I can configure the node to use a fixed time for the start and "sunset" for the end of the timer. 
For example: I want to open a blind at 6:30 and close it at sunset.

An additional bonus feature could be to add something like: 

- starttype is sunrise (+/- offset) but not later than / before 6:30
- endtype is sunset (+/- offset) but not later than / before 20:00

**Comment by fellinga** [comment]
Hi Peter,

I am currently not allowing mixed time frames because validation is almost impossible. Say, the user sets a timer that statically starts at 06:30 and ends at sunrise (07:00 as of today). Validation would say ok it runs 30 minutes - save. A few weeks later sunrise might happens before the statically configured start time and you would end up having a timer that runs from 06:30 to 06:25 or so.

There is another mode - the event mode - in event mode you can create an event that does a certain thing at a specific time independently of other events. That would make your blind scenario possible -> Event1: 06:30 open blinds, Event2: sunset close blinds.

Please let me know if this helps!

**Comment by PeterAustria** [comment]
Hi Fellinga,
thanks a lot for your quick reply and your explanation.
And yes, in event mode I was able to create the necessary scenario.

**Comment by HubertusH** [comment]
Solving the problem with the event node is messy. If - to give another example - light on at 6:00 am and off after sunrise. If now the sunrise is BEFORE 6:00 the light should not turn on at all. In the case of the proposed event mode, the light would turn on at 6:00 but not off again (only the next day after sunrise and then immediately on again when 6:00 is reached).

The check could simply ignore the event in case of negative time differences/running times.

Best regards
Hubertus

**Comment by fellinga** [comment]
FYI: It's now possible to mix start and end time but without any check when they overlap.
