### ISSUE TITLE
please use cronjob

### ISSUE THREAD

**Issue by d0d04m3** [fellinga/node-red-contrib-ui-time-scheduler#42]
hi please changed default time to
time + date and more option like cronjob

**Comment by fellinga** [comment]
Hi @d0d04m3,

the node is constantly improving and receives new features all the time. I am currently not planning on adding a date since that would not be a recurring event. There is a possibility though that I'll add a selection for specific weeks or maybe months but that is still in the backlog.

This node was made to let users, even without technical background, schedule events at the frontend, therefore I won't add cron. 

Please let me know if you need anything else.

**Comment by d0d04m3** [comment]
> Hi @d0d04m3,
> 
> the node is constantly improving and receives new features all the time. I am currently not planning on adding a date since that would not be a recurring event. There is a possibility though that I'll add a selection for specific weeks or maybe months but that is still in the backlog.
> 
> This node was made to let users, even without technical background, schedule events at the frontend, therefore I won't add cron.
> 
> Please let me know if you need anything else.

But
Thus, events had to be repeated every day at the appointed hour
What if the user does not want to execute the event on a certain date
Your graphic node allows users to control events graphically for those who don't have an angular background but your work needs a lot of improvement why not make your node can work with cron node
