### ISSUE TITLE
SUNEVENT in Normal-Mode ... Missing Custom option

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [fellinga/node-red-contrib-ui-time-scheduler#46]
Awesome update with all the SUNEVENTS...thx a lot .. works great in EVENT-Mode

In normal mode the CUSTOM option is missing, therefore you always need 2 SUNEVENTS in your schedule (e.g. SUNSET till 10pm is not possible)

Addtionally:
Once set for SUNEVENTS ...it is not possible to change back to time-based schedule (I guess due to missing CUSTOM option)

great job and very quick response ... thx a lot

**Comment by fellinga** [comment]
I already linked the reason why it is "missing" in the other issue that you've opened.

Please see https://github.com/fellinga/node-red-contrib-ui-time-scheduler/issues/33 again.

**Comment by xX-Nexus-Xx** [comment]
thx .. you still can have 2 SUNEVENTS .. e.g. SUNSET till 10pm is not possible

but i can work-around with SUNSET till SUNSET+2h

;) thx a lot

**Comment by fellinga** [comment]
> you still can have 2 SUNEVENTS .. e.g. SUNSET till 10pm is not possible
Sunset till 10pm are not two sun events. 

Sunset till 10pm would be a start sun event and a fixed stop time and I am not allowing it because of what I answered in the link that I have posted. It says that I do not allow MIXED time frames in default mode because validation is almost impossible - but you can easily archive that with event mode.
