### ISSUE TITLE
Possible to allow more flexible styling?

### ISSUE THREAD

**Issue by eddyyanto** [fellinga/node-red-contrib-ui-time-scheduler#55]
I am showing the scheduler UI on an iPad and the text and icon seemed small. I tried to add custom styling using template node but it seemed that some of the styling are hard-encoded in the HTML element.

Here's the screenshot of the UI and the css styling that I used.

```
<style>
body.nr-dashboard-theme {
    font-size: 25px !important;
}
md-list-item.md-2-line .md-list-item-text{
    height:50px;
}
</style>
```

![nr](https://user-images.githubusercontent.com/372538/132933008-d73a45b1-6f2e-40bf-96be-2220412fb9c6.png)

 Is there a way to scale the whole UI such as the rows, text and icon bigger or hide a certain button?

**Comment by fellinga** [comment]
Hi @eddyyanto,

thanks for reaching out to me. I just pushed 1.16.0 where I slightly modified the CSS so that overriding should be a little easier.
Try something like this:

```
<style>
body.nr-dashboard-theme {
    font-size: 25px !important;
}
md-list-item.md-2-line .md-list-item-text{
    height:120px;
}
#ui-ts-e0d75601502b9a02 .weekDay{
    width: 70px !important;
    line-height: 70px !important;
}
</style>
```


![Capture](https://user-images.githubusercontent.com/26927863/134684891-b95acc16-1318-449b-9352-f6b873c52c7b.PNG)
This would improve the readability of the list items for example.


You can see the classes that I am using [here](https://github.com/fellinga/node-red-contrib-ui-time-scheduler/blob/d75ee46a57a9681cdf5b6aaa2640d28734734796/time-scheduler.js#L35).

Let me know how it goes!

**Comment by eddyyanto** [comment]
Thanks @fellinga! That helped! I ended up with your suggestion on overriding the CSS classes as well as hard-coding them in the module file. As my use case is a slightly different due to the embedded browser rendering engine that made the text and UI far too small compared to the standard mobile browser.

Granted, I understood the hard-coding might be overwritten should there be future update to the module.
