### ISSUE TITLE
Node Output Labelling query

### ISSUE THREAD

**Issue by GwelforBodad** [fellinga/node-red-contrib-ui-time-scheduler#57]
Thanks for the excellent node which I'm trying to implement today.  It took me a while to realise that the first device goes to the second output and that the second device goes to the third output.
![Project1](https://user-images.githubusercontent.com/54096574/134940253-55b55c69-73fa-41ed-ac73-ecaf721d88d9.png)
Your documentation does state this but I was initially confused as it's different from what I've seen in the past.  Perhaps a default "device 1" that cannot be deleted should appear in the devices box, maybe stating that it's the internal JSON scheduling output, on Output 1.  Users would then be able to add their own devices knowing that the first was to be connected to Output 2 etc?
The actual JSON schedule also confused me initially as Device 1 seems to be "output":"0" while device 2 and 3 are outputs 1 and 2 respectively.  I respect that you've invested a lot of time and effort to get this to work as well as it does and I also understand that you cannot make fundamental changes because of backward compatibility but hope that my feedback may lead to a change of some sort.

**Comment by fellinga** [comment]
Hi @GwelforBodad,

thanks for the feedback. 

I have just pushed an update to fix the device index in the node-red editor. Because of backwards compatibility I won't change the generated JSON... "output":"0" for the first device still makes sense though if we think about it as "deviceoutput":0 since its the first device and we start counting with 0.
