### ISSUE TITLE
Wrong day when schedule starts at midnight 

### ISSUE THREAD

**Issue by mongojarle** [fellinga/node-red-contrib-ui-time-scheduler#73]
Okay, I'm not very good at explaining, but when I have a schedule set to start at midnight, the scheduler will not select the correct day, but the very next day.

If I inject the following code, I expect the day to be Thursday, but it will select Friday.

"{"timers":[{"starttime":1644447600000,"days":[0,0,0,0,1,0,0],"output":"0","endtime":1644458400000}],"settings":{}}"

days = [sun, mon, tue, wed, **thu**, fri, sat], and this works for any other schedule, except when it starts at midnight. (This does not respect the settings in the node "First day", but not a problem).
1644447600000 = Thursday, February 10, 2022 0:00:00 [GMT+01:00]
1644458400000 = Thursday, February 10, 2022 3:00:00 [GMT+01:00]

The above code will produce the following schedule:
![scheduler](https://user-images.githubusercontent.com/41956509/153363512-ac73068b-4fd3-4f31-bc69-885832392eff.png)

There will not be any output from the scheduler on Thursday.

**Comment by mongojarle** [comment]
Hi, thank you for a quick answer. Not sure if I understand why this happens, but I have made changes to my code so it will store the correct day when the schedule starts at midnight. It was just a behavior I did not anticipate.

**Comment by fellinga** [comment]
Glad I could help.
Going to close this issue now, let me know if you need anything else!

In case you are interested into details here: the days have to be stored in UTC time so that I can calculate the correct day for different users from different countries. If someone from UTC-1 visits your website then this person should see "Wednesday 22:00" instead of Thursday 00:00.
