### ISSUE TITLE
Dropdown Size of Day Selection to big

### ISSUE THREAD

**Issue by Makiese** [fellinga/node-red-contrib-ui-time-scheduler#84]
Hello,

is it possible to reduce the width of the selection menu for the days of the week? In the view (for example on the smartphone) the checkbox is cut off in front because the main menu covers it. Thanks in advance.

![2022-10-02 13_32_58-Window](https://user-images.githubusercontent.com/42896364/193451819-72bf4b25-3bec-4c96-8526-f24eb3ba1f4f.png)

![2022-10-02 13_30_01-Window](https://user-images.githubusercontent.com/42896364/193451789-511196a9-81e7-40a6-b7de-57074cee3ae4.png)

**Comment by fellinga** [comment]
Hi @Makiese,

thanks for creating an issue. I was able to reproduce the problem with the ui-time-scheduler as well as with default node-red-dashboard components. The issue lies in the framework and I have just created a pull request at the @node-red-dashboard project. The problem should be gone after it has been merged and released.

https://github.com/node-red/node-red-dashboard/pull/775

**Comment by Makiese** [comment]
HI @fellinga 

thank you for your quick Support.
