### ISSUE TITLE
Negativ Offset not possible?

### ISSUE THREAD

**Issue by Makiese** [fellinga/node-red-contrib-ui-time-scheduler#85]
Hi,

I have more a question instead of reporting an issue. How can I set a negativ Time Offset vallue.
I want to triggern an event at special time Event with a minus Offset of 15 minutes. 

But its not possible to input minus sign.

Thanks for help in advance.

![20221012_213350](https://user-images.githubusercontent.com/42896364/195432081-3b5cfeb6-dbd3-4431-a26e-c427a1f51196.jpg)

**Comment by fellinga** [comment]
Hi @Makiese,

it definitely works on a pc (and also on my phone). It seems that your phone sees that the input field is of type number and therefore changes your keyboard to a number keyboard that unfortunately does not support negative numbers. 
Just to make sure that the node works, could copy and paste "-30" into this field and tell me if that worked for you?

**Comment by Makiese** [comment]
Hi, thanks for the late reply. You are defnitly  right. Copy paste a negative valie works. The Problem is the numpad Keyboard, weich has no minus sign.

**Comment by fellinga** [comment]
I just tried again on my Android as well as on an iPad and both show the minus sign. 

![android](https://github.com/fellinga/node-red-contrib-ui-time-scheduler/assets/26927863/59fee322-fae8-4dfe-970b-20aa6c1d0601)

It seems to be a Samsung related issue, since I found a lot of complaints about "Samsung keyboard missing minus sign". At this point I can only recommend to change your default keyboard to for example the [Google Keyboard](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin&hl=de ).
