### ISSUE TITLE
GUI size not respecting the settings.

### ISSUE THREAD

**Issue by Just-another-pleb** [fellinga/node-red-contrib-ui-time-scheduler#9]
I set the width to 6 but it seems to be 7 wide.

![Screenshot from 2020-11-23 20-07-54](https://user-images.githubusercontent.com/39888280/99944884-c0b8a400-2dc7-11eb-9832-2cae6203498f.png)

![Screenshot from 2020-11-23 20-08-03](https://user-images.githubusercontent.com/39888280/99944891-c57d5800-2dc7-11eb-8adf-22ef600af086.png)

**Comment by fellinga** [comment]
Are you using a custom theme? Could you check if it also happens without it?

**Comment by Just-another-pleb** [comment]
To the best of my knowledge:  No.  Only the DARK one which comes with NR.

**Comment by fellinga** [comment]
Ok I figured it out. It happens if "**Angular theme in ui_template**" is enabled. 
![theme](https://user-images.githubusercontent.com/26927863/100013587-5eff3680-2dd5-11eb-926d-817840203ddd.png)
You can switch to "**Node-RED theme everywhere**" in order to avoid that for now. 

Thanks for pointing it out... I am definitely going to fix this in one of the next updates.

**Comment by Just-another-pleb** [comment]
I had a theme in the edit screen (midnight-red).

I disabled that and restarted NR.

Same problem.

For the sake of everyone's sanity, I will try it with chrome.
(Strike that, sorry.   My main machine is down and I don't have Chrome installed on this.)
Saw your latest reply.

Yes, I am using Angular in ui template.
